### PR TITLE
Allow usage of STARTTLS/SSL without enabling authentication

### PR DESCRIPTION
**Pull request by ducalex**
This patch makes the SMTP encryption (STARTTLS/SSL) setting independent of authentication.

I did my best to update the translations but a quick review would be appreciated!

### CODE REVIEW

**Comment by grote** [comment]
Thanks a lot for the PR!

> This patch makes the SMTP encryption (STARTTLS/SSL) setting independent of authentication.

What's the use-case for that?

> I did my best to update the translations but a quick review would be appreciated!

Please don't. They are managed via Transifex.

**Comment by ducalex** [comment]
> What's the use-case for that?

One concrete example would be when connecting directly to the MX of the recipient's email address. The server will accept the email without a login because it's a local delivery. So we get an encrypted connection to the server AND we don't have to store SMTP credentials on the phone at all.

> Please don't. They are managed via Transifex.

Should I remove everything except the English version? Please let me know how to proceed (If you choose to accept my pull request!).

Thanks

**Comment by grote** [comment]
> One concrete example would be when connecting directly to the MX of the recipient's email address. The server will accept the > email without a login because it's a local delivery. So we get an encrypted connection to the server AND we don't have to store > SMTP credentials on the phone at all.

That would be nice. Did you test this against some SMTP servers? Does it work with gmail?

> Should I remove everything except the English version? Please let me know how to proceed (If you choose to accept my pull request!).

Could we maybe drop the English change as well, to me it doesn't seem to be terribly necessary.

**Comment by ducalex** [comment]
> 
> That would be nice. Did you test this against some SMTP servers? Does it work with gmail?
> 

I have tested gmail, protonmail, firefox relay, my ISP, and my personal mail server.

On port 25: They all accept STARTTLS and they all accept the delivery without authentication. Gmail also ended up in spam at first.

On port 587: They all accept STARTTLS but only my ISP and my personal mail server accepted the delivery without authentication (not surprising as 587 is meant for submission).

**Comment by grote** [comment]
Cool, sounds good! Thanks for your contribution!

**Pull request merged**
